"""add language to user

Revision ID: 09516ae58645
Revises: 263a3cea6f1b
Create Date: 2024-12-12 13:55:38.453789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09516ae58645'
down_revision = '263a3cea6f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
